services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped

    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://${N8N_HOST}/
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=America/Bogota
      - TZ=America/Bogota

    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
